### ISSUE TITLE
I started up the game and it gives me this

### ISSUE THREAD

**Issue by Slinks02** [That1M8Head/Sonic-LockandLoad#9] opened 2022-05-20 07:36 UTC
**What happened?**
Explain what happened clearly and concisely.

**How did it happen?**
Explain what you did that led to whatever breaking.

**What was supposed to happen?**

**Screenshots**

**Platform information**
 - OS (Windows/macOS/Linux): 
 - GZDoom version (e.g. 4.7.1): 
 - Sonic: Lock & Load version (e.g. 1.3.2, or edge): 

**Anything else?**

**Comment by Slinks02** [comment] 2022-05-20 07:37
![image](https://user-images.githubusercontent.com/105909264/169477802-8bd042f0-58c5-42ac-b1b7-bef4d9d09f84.png)

**Comment by AeriaVelocity** [comment] 2022-05-20 07:37
Are you using GZDoom or LZDoom? (Also, next time, can you please edit the template?)

**Comment by Slinks02** [comment] 2022-05-20 07:46
GZDoom

**Comment by AeriaVelocity** [comment] 2022-05-20 07:47
What version of GZDoom and what OS?

**Comment by Slinks02** [comment] 2022-05-20 07:49
4.7.1 and Windows

**Comment by AeriaVelocity** [comment] 2022-05-20 07:52
Well, I'm not sure what the issue is, then -- DamageType has existed for a while now.

**Comment by AeriaVelocity** [comment] 2022-06-08 13:52
Closing issue -- nothing can be done on my end

**Closed as completed by AeriaVelocity** 2022-06-08 13:52 UTC
Labels: Something Broke, It's No Use
